### ISSUE TITLE
Not working with 5.8.7 FBG5

### ISSUE THREAD

**Issue by nixprosoft** [ArtificalSUN/MKS-WIFI_PS_uploader#7]
Binary stop working with FBG5 after upgrade from 5.8.4 to 5.8.7.
Hands on "Starting upload"

**Comment by nixprosoft** [comment]
![2022-01-19 10-13-34 Скриншот экрана](https://user-images.githubusercontent.com/5313478/150537385-7eb4f387-186e-46bb-9795-ef57d54645a3.png)

**Comment by nixprosoft** [comment]
WiFi on printer works. Web-interface on printer is working.

**Comment by nixprosoft** [comment]
On Marlin 2.0.9.3 the same problem.

**Comment by Goodsmileduck** [comment]
While trying to debug it with python script, I found that it can't decode Cyrillic symbols from comments. Here a fix for that https://github.com/ArtificalSUN/MKS-WIFI_PS_uploader/pull/8

**Comment by ArtificalSUN** [comment]
Thx @Goodsmileduck , I've merged your fix. Better now than never 😃

**Comment by megapro17** [comment]
![image](https://user-images.githubusercontent.com/16743370/189457302-ea8be944-bc3a-42c2-9550-e373d9dd49f1.png)
Still not working 😐
